"""initial schema v1

Revision ID: 843e8a8e704f
Revises: 
Create Date: 2026-09-05 12:54:44.462237

"""
from typing import Sequence, Union

import app.core.db as _dbtypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '843e8a8e704f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_events',
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('domain_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domain_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_domain_events_user_id'), ['user_id'], unique=False)

    op.create_table('knowledge_points',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('subject', sa.String(length=32), nullable=True),
    sa.Column('grade', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['knowledge_points.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_points_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_knowledge_points_subject'), ['subject'], unique=False)

    op.create_table('outbox_events',
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('processed_at', _dbtypes.UTCDateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbox_events_event_type'), ['event_type'], unique=False)

    op.create_table('question_sources',
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('license', sa.String(length=120), nullable=True),
    sa.Column('retrieved_at', _dbtypes.UTCDateTime(), nullable=True),
    sa.Column('original_id', sa.String(length=160), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('ai_jobs',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', _dbtypes.UTCDateTime(), nullable=True),
    sa.Column('finished_at', _dbtypes.UTCDateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('attachments',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_user_id'), ['user_id'], unique=False)

    op.create_table('courses',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('teacher', sa.String(length=80), nullable=True),
    sa.Column('grade', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=9), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('deleted_at', _dbtypes.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index('ix_courses_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_user_id'), ['user_id'], unique=False)

    op.create_table('knowledge_point_aliases',
    sa.Column('knowledge_point_id', sa.String(length=36), nullable=False),
    sa.Column('alias', sa.String(length=160), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias', name='uq_kp_alias')
    )
    with op.batch_alter_table('knowledge_point_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_point_aliases_knowledge_point_id'), ['knowledge_point_id'], unique=False)

    op.create_table('practice_sets',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('created_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('practice_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_sets_user_id'), ['user_id'], unique=False)

    op.create_table('questions',
    sa.Column('subject', sa.String(length=32), nullable=True),
    sa.Column('grade', sa.String(length=32), nullable=True),
    sa.Column('question_type', sa.String(length=24), nullable=False),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('deleted_at', _dbtypes.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['question_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_subject'), ['subject'], unique=False)
        batch_op.create_index('ix_questions_subject_diff', ['subject', 'difficulty'], unique=False)

    op.create_table('rag_documents',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=32), nullable=True),
    sa.Column('grade', sa.String(length=32), nullable=True),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rag_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rag_documents_user_id'), ['user_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('revoked_at', _dbtypes.UTCDateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('review_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('onboarded', sa.Boolean(), nullable=False),
    sa.Column('grade', sa.String(length=32), nullable=True),
    sa.Column('primary_subject', sa.String(length=32), nullable=True),
    sa.Column('daily_minutes', sa.Integer(), nullable=False),
    sa.Column('preferred_time', sa.String(length=8), nullable=True),
    sa.Column('target_retention', sa.Float(), nullable=False),
    sa.Column('exam_date', _dbtypes.UTCDateTime(), nullable=True),
    sa.Column('density_preference', sa.String(length=16), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_knowledge_mastery',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('knowledge_point_id', sa.String(length=36), nullable=False),
    sa.Column('mastery', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', _dbtypes.UTCDateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'knowledge_point_id', name='uq_user_kp_mastery')
    )
    with op.batch_alter_table('user_knowledge_mastery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_knowledge_mastery_knowledge_point_id'), ['knowledge_point_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_knowledge_mastery_user_id'), ['user_id'], unique=False)

    op.create_table('user_preferences',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('daily_review_minutes', sa.Integer(), nullable=False),
    sa.Column('preferred_review_time', sa.String(length=8), nullable=False),
    sa.Column('target_retention', sa.Float(), nullable=False),
    sa.Column('exam_date', _dbtypes.UTCDateTime(), nullable=True),
    sa.Column('primary_subject', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('grade', sa.String(length=32), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('ai_runs',
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('agent_version', sa.String(length=32), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('started_at', _dbtypes.UTCDateTime(), nullable=True),
    sa.Column('finished_at', _dbtypes.UTCDateTime(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['ai_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_runs_job_id'), ['job_id'], unique=False)

    op.create_table('attempts',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('practice_set_id', sa.String(length=36), nullable=True),
    sa.Column('review_task_id', sa.String(length=36), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('hint_count', sa.Integer(), nullable=False),
    sa.Column('answer_change_count', sa.Integer(), nullable=False),
    sa.Column('grading_source', sa.String(length=16), nullable=True),
    sa.Column('attempted_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['practice_set_id'], ['practice_sets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempts_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_review_task_id'), ['review_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_attempts_user_time', ['user_id', 'attempted_at'], unique=False)

    op.create_table('lessons',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=32), nullable=True),
    sa.Column('grade', sa.String(length=32), nullable=True),
    sa.Column('teacher', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', _dbtypes.UTCDateTime(), nullable=True),
    sa.Column('ended_at', _dbtypes.UTCDateTime(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('deleted_at', _dbtypes.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lessons_course_id'), ['course_id'], unique=False)
        batch_op.create_index('ix_lessons_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_lessons_user_id'), ['user_id'], unique=False)

    op.create_table('memory_states',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('stability', sa.Float(), nullable=False),
    sa.Column('retrievability', sa.Float(), nullable=True),
    sa.Column('last_review_at', _dbtypes.UTCDateTime(), nullable=True),
    sa.Column('next_review_at', _dbtypes.UTCDateTime(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('lapse_count', sa.Integer(), nullable=False),
    sa.Column('last_rating', sa.Integer(), nullable=True),
    sa.Column('suspended', sa.Boolean(), nullable=False),
    sa.Column('scheduler_version', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id', name='uq_memory_state')
    )
    with op.batch_alter_table('memory_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_states_next_review_at'), ['next_review_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_states_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_states_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_ms_user_due', ['user_id', 'next_review_at'], unique=False)

    op.create_table('practice_set_items',
    sa.Column('practice_set_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['practice_set_id'], ['practice_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('practice_set_id', 'position', name='uq_ps_item_pos')
    )
    with op.batch_alter_table('practice_set_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_set_items_practice_set_id'), ['practice_set_id'], unique=False)

    op.create_table('question_analyses',
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('tree_payload', sa.JSON(), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_table('question_knowledge_points',
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('knowledge_point_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'knowledge_point_id', name='uq_question_kp')
    )
    with op.batch_alter_table('question_knowledge_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_knowledge_points_knowledge_point_id'), ['knowledge_point_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_knowledge_points_question_id'), ['question_id'], unique=False)

    op.create_table('rag_chunks',
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=True),
    sa.Column('question_id', sa.String(length=36), nullable=True),
    sa.Column('knowledge_point_ids', sa.JSON(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['rag_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_rag_chunk')
    )
    with op.batch_alter_table('rag_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rag_chunks_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_chunks_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_chunks_question_id'), ['question_id'], unique=False)

    op.create_table('exercise_searches',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=True),
    sa.Column('knowledge_point_id', sa.String(length=36), nullable=True),
    sa.Column('query_payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('agent', sa.String(length=64), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercise_searches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_searches_user_id'), ['user_id'], unique=False)

    op.create_table('knowledge_tree_snapshots',
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('tree_payload', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['question_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_tree_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_tree_snapshots_question_id'), ['question_id'], unique=False)

    op.create_table('lesson_knowledge_points',
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('knowledge_point_id', sa.String(length=36), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_segment_ids', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'knowledge_point_id', name='uq_lesson_kp')
    )
    with op.batch_alter_table('lesson_knowledge_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_knowledge_points_knowledge_point_id'), ['knowledge_point_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_knowledge_points_lesson_id'), ['lesson_id'], unique=False)

    op.create_table('lesson_summaries',
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id')
    )
    op.create_table('recordings',
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('finalized_at', _dbtypes.UTCDateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recordings_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recordings_user_id'), ['user_id'], unique=False)

    op.create_table('review_tasks',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('memory_state_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('due_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.String(length=10), nullable=False),
    sa.Column('completed_at', _dbtypes.UTCDateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['memory_state_id'], ['memory_states.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_tasks_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_tasks_scheduled_date'), ['scheduled_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_tasks_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_rt_user_status_due', ['user_id', 'status', 'due_at'], unique=False)

    op.create_table('user_questions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('origin', sa.String(length=24), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('added_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id', name='uq_user_question')
    )
    with op.batch_alter_table('user_questions', schema=None) as batch_op:
        batch_op.create_index('ix_uq_user_added', ['user_id', 'added_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_questions_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_questions_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_questions_user_id'), ['user_id'], unique=False)

    op.create_table('exercise_search_results',
    sa.Column('search_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('relevance_reason', sa.Text(), nullable=True),
    sa.Column('band', sa.String(length=16), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_id'], ['exercise_searches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercise_search_results', schema=None) as batch_op:
        batch_op.create_index('ix_esr_search_score', ['search_id', 'score'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercise_search_results_search_id'), ['search_id'], unique=False)

    op.create_table('review_logs',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('review_task_id', sa.String(length=36), nullable=True),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('attempt_id', sa.String(length=36), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('scheduler_version', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_task_id'], ['review_tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_logs_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_logs_user_id'), ['user_id'], unique=False)

    op.create_table('transcript_segments',
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('recording_id', sa.String(length=36), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('speaker', sa.String(length=32), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', _dbtypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'sequence', name='uq_segment_lesson_seq')
    )
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.create_index('ix_segments_lesson_start', ['lesson_id', 'start_ms'], unique=False)
        batch_op.create_index(batch_op.f('ix_transcript_segments_lesson_id'), ['lesson_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcript_segments_lesson_id'))
        batch_op.drop_index('ix_segments_lesson_start')

    op.drop_table('transcript_segments')
    with op.batch_alter_table('review_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_review_logs_question_id'))

    op.drop_table('review_logs')
    with op.batch_alter_table('exercise_search_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_search_results_search_id'))
        batch_op.drop_index('ix_esr_search_score')

    op.drop_table('exercise_search_results')
    with op.batch_alter_table('user_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_questions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_questions_question_id'))
        batch_op.drop_index(batch_op.f('ix_user_questions_lesson_id'))
        batch_op.drop_index('ix_uq_user_added')

    op.drop_table('user_questions')
    with op.batch_alter_table('review_tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_rt_user_status_due')
        batch_op.drop_index(batch_op.f('ix_review_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_review_tasks_scheduled_date'))
        batch_op.drop_index(batch_op.f('ix_review_tasks_question_id'))

    op.drop_table('review_tasks')
    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recordings_user_id'))
        batch_op.drop_index(batch_op.f('ix_recordings_lesson_id'))

    op.drop_table('recordings')
    op.drop_table('lesson_summaries')
    with op.batch_alter_table('lesson_knowledge_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_knowledge_points_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_knowledge_points_knowledge_point_id'))

    op.drop_table('lesson_knowledge_points')
    with op.batch_alter_table('knowledge_tree_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_tree_snapshots_question_id'))

    op.drop_table('knowledge_tree_snapshots')
    with op.batch_alter_table('exercise_searches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_searches_user_id'))

    op.drop_table('exercise_searches')
    with op.batch_alter_table('rag_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rag_chunks_question_id'))
        batch_op.drop_index(batch_op.f('ix_rag_chunks_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_rag_chunks_document_id'))

    op.drop_table('rag_chunks')
    with op.batch_alter_table('question_knowledge_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_knowledge_points_question_id'))
        batch_op.drop_index(batch_op.f('ix_question_knowledge_points_knowledge_point_id'))

    op.drop_table('question_knowledge_points')
    op.drop_table('question_analyses')
    with op.batch_alter_table('practice_set_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practice_set_items_practice_set_id'))

    op.drop_table('practice_set_items')
    with op.batch_alter_table('memory_states', schema=None) as batch_op:
        batch_op.drop_index('ix_ms_user_due')
        batch_op.drop_index(batch_op.f('ix_memory_states_user_id'))
        batch_op.drop_index(batch_op.f('ix_memory_states_question_id'))
        batch_op.drop_index(batch_op.f('ix_memory_states_next_review_at'))

    op.drop_table('memory_states')
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lessons_user_id'))
        batch_op.drop_index('ix_lessons_user_created')
        batch_op.drop_index(batch_op.f('ix_lessons_course_id'))

    op.drop_table('lessons')
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_attempts_user_time')
        batch_op.drop_index(batch_op.f('ix_attempts_user_id'))
        batch_op.drop_index(batch_op.f('ix_attempts_review_task_id'))
        batch_op.drop_index(batch_op.f('ix_attempts_question_id'))

    op.drop_table('attempts')
    with op.batch_alter_table('ai_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_runs_job_id'))

    op.drop_table('ai_runs')
    op.drop_table('user_profiles')
    op.drop_table('user_preferences')
    with op.batch_alter_table('user_knowledge_mastery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_knowledge_mastery_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_knowledge_mastery_knowledge_point_id'))

    op.drop_table('user_knowledge_mastery')
    op.drop_table('review_profiles')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_jti'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('rag_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rag_documents_user_id'))

    op.drop_table('rag_documents')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index('ix_questions_subject_diff')
        batch_op.drop_index(batch_op.f('ix_questions_subject'))
        batch_op.drop_index(batch_op.f('ix_questions_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_questions_content_hash'))

    op.drop_table('questions')
    with op.batch_alter_table('practice_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practice_sets_user_id'))

    op.drop_table('practice_sets')
    with op.batch_alter_table('knowledge_point_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_point_aliases_knowledge_point_id'))

    op.drop_table('knowledge_point_aliases')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_user_id'))
        batch_op.drop_index('ix_courses_user_created')

    op.drop_table('courses')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_user_id'))

    op.drop_table('attachments')
    with op.batch_alter_table('ai_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_jobs_job_type'))

    op.drop_table('ai_jobs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('subjects')
    op.drop_table('question_sources')
    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbox_events_event_type'))

    op.drop_table('outbox_events')
    with op.batch_alter_table('knowledge_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_points_subject'))
        batch_op.drop_index(batch_op.f('ix_knowledge_points_slug'))

    op.drop_table('knowledge_points')
    with op.batch_alter_table('domain_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domain_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_domain_events_event_type'))

    op.drop_table('domain_events')
    # ### end Alembic commands ###
